import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ApolloWrapper from '@/src/context/ApolloWrapper'
import Navbar from '@/src/components/Layout/Navbar/navbar'
import Footer from '@/src/components/Layout/Footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
            <Navbar />
            {children}
            <Footer />
        </ApolloWrapper>
      </body>
    </html>
  )
}
